kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mta-keycloak
  namespace: openshift-mta
  labels:
    app: keycloak
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: keycloak
    weight: 100
  port:
    targetPort: keycloak
  tls:
    termination: passthrough
  wildcardPolicy: None
