apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: postgres-secrets
  namespace: postgres
  envs:
  - postgres.properties

- name: postgres-secrets
  envs:
  - postgres.properties

resources:
- postgres.yaml
- ../sonataflow/

images:
- name: quay.io/kiegroup/kogito-serverless-operator
  newTag: "1.44"
- name: quay.io/kiegroup/kogito-data-index-postgresql
  newTag: "1.44.1"
- name: quay.io/kiegroup/kogito-jobs-service-postgresql
  newTag: "1.44.1"
- name: postgres
  newTag: "15"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: sonataflow-runtime-ddl
    namespace: postgres
    files:
      - V1.35.0__create_runtime_PostgreSQL.sql