apiVersion: v1
data:
  application.properties: |
    kogito.service.url=${kubernetes:services.v1/greeting}
    quarkus.log.category."io.smallrye.reactive.messaging".level = DEBUG
    quarkus.log.category."org.kie".level = DEBUG
    quarkus.log.category."io.quarkus.reactivemessaging".level = DEBUG
    quarkus.log.category."io.vertx".level = DEBUG
    quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-db-service.postgres:5432/sonataflow
    quarkus.datasource.username=sonataflow
    quarkus.datasource.password=sonataflow
kind: ConfigMap
metadata:
  labels:
    app: greeting
  name: greeting-props
