apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: jobs-service-properties
  files:
  - application.properties

resources:
- jobs-service.yaml
