apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: assessment-func
spec:
  template:
    spec:
      containers:
      - image: "quay.io/{username}/assessment-func:latest"
        ports:
        - containerPort: 8080
