apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: assessment-func
spec:
  template:
    spec:
      containers:
      - image: "quay.io/aketcha/assessment-func:1.0.0-SNAPSHOT"
        ports:
        - containerPort: 8080
