{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
{{- end }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.jiralistener.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: jira-listener
{{- if .Values.letsEncryptCertificate }}
  annotations:
    serving.knative.openshift.io/disableRoute: "true"
{{- end }}
spec:
  template:
    metadata:
      labels:
        app: jira-listener
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: {{ .Values.jiralistener.image }}
          imagePullPolicy: Always
          name: jira-listener
          resources:
            limits:
              memory: 200Mi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: escalation-config
  namespace: {{ .Values.namespace.name }}
data:
  JIRA_URL: {{ .Values.escalationSwf.jira.url}}
  JIRA_PROJECT: {{ .Values.escalationSwf.jira.project}}
  JIRA_ISSUE_TYPE: '{{ .Values.escalationSwf.jira.issueType}}'
  ESCALATION_TIMEOUT_SECONDS: '{{ .Values.escalationSwf.escalationTimeoutSeconds}}'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.escalationSwf.name }}-props
  namespace: {{ .Values.namespace.name }}
{{- $fileName := printf "resources/%s" .Values.escalationSwf.ticketingServiceProps }}
data:
  application.properties: |-
{{ .Files.Get "resources/application.properties" | indent 4 }}
{{ .Files.Get $fileName | indent 4 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: escalation-specs
  namespace: {{ .Values.namespace.name }}
data:
{{ (tpl (.Files.Glob "resources/specs/*").AsConfig .) | indent 2 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: escalation-subflow
  namespace: {{ .Values.namespace.name }}
data:
# TODO Replace original id with ticketing-service?
  ticketing-service.sw.yaml: |-
{{- $fileName := printf "resources/%s" .Values.escalationSwf.ticketingServiceSubflow }}
{{ .Files.Get $fileName | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: escalation-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  JIRA_USERNAME: {{ .Values.escalationSwf.jira.username}}
  JIRA_API_TOKEN: {{ .Values.escalationSwf.jira.apiToken}}
  MAILTRAP_API_TOKEN: {{ .Values.escalationSwf.mailTrap.apiToken}}
  MAILTRAP_INBOX_ID: '{{ .Values.escalationSwf.mailTrap.inboxId}}'
  OCP_API_SERVER_URL: {{ .Values.escalationSwf.ocp.apiServerUrl}}
  OCP_API_SERVER_TOKEN: {{ .Values.escalationSwf.ocp.apiServerToken}}
---
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: {{ .Values.escalationSwf.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: escalation-swf
  annotations:
    sonataflow.org/description: Escalation workflow
    sonataflow.org/version: 0.0.1
    sonataflow.org/profile: {{ .Values.escalationSwf.profile }} 
spec:
  resources: 
    configMaps:
      - configMap:
          name: escalation-specs 
        workflowPath: specs 
      - configMap:
          name: escalation-subflow 
  flow:
{{ .Files.Get "resources/ticketEscalation.sw.yaml" | indent 4 }}
  podTemplate:
    container:
      envFrom:
        - configMapRef:
            name: escalation-config
        - secretRef:
            name: escalation-secret    
---
{{- if .Values.eventdisplay.enabled }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: {{ .Values.namespace.name }}
  labels:
    app: event-display
spec:
  template:
    metadata:
      labels:
        app: event-display
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
          name: event-display
          resources:
            limits:
              memory: 200Mi
{{- end }}
---
{{- if .Values.letsEncryptCertificate }}
{{- $cluster := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- $domain := "UNKNOWN" }}
{{- if hasKey $cluster "spec" }}
  {{- if hasKey $cluster.spec "domain" }}
    {{- $domain = $cluster.spec.domain}}
  {{- end }}
{{- end }}

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 600s 
    kubernetes.io/tls-acme: "true"
  name: {{ .Values.jiralistener.name }} 
  namespace: knative-serving-ingress 
spec:
  host: {{ .Values.jiralistener.name }}-{{ .Values.namespace.name }}.{{ $domain }}
  port:
    targetPort: http2
  to:
    kind: Service
    name: kourier
    weight: 100
  wildcardPolicy: None
{{- end }}
