{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
{{- end }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.jiralistener.name }}
  namespace: {{ .Values.namespace.name }}
{{- if .Values.letsEncryptCertificate }}
  annotations:
    serving.knative.openshift.io/disableRoute: "true"
{{- end }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.jiralistener.name }}
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: {{ .Values.jiralistener.image }}
          imagePullPolicy: Always
          name: user-container
          resources:
            limits:
              memory: 200Mi
---
{{- if .Values.eventdisplay.enabled }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: {{ .Values.namespace.name }}
spec:
  template:
    metadata:
      labels:
        app: event-display
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
          name: user-container
          resources:
            limits:
              memory: 200Mi
{{- end }}
---
{{- if .Values.letsEncryptCertificate }}
{{- $cluster := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- $domain := "UNKNOWN" }}
{{- if hasKey $cluster "spec" }}
  {{- if hasKey $cluster.spec "domain" }}
    {{- $domain = $cluster.spec.domain}}
  {{- end }}
{{- end }}

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 600s 
    kubernetes.io/tls-acme: "true"
  name: {{ .Values.jiralistener.name }} 
  namespace: knative-serving-ingress 
spec:
  host: {{ .Values.jiralistener.name }}-{{ .Values.namespace.name }}.{{ $domain }}
  port:
    targetPort: http2
  to:
    kind: Service
    name: kourier
    weight: 100
  wildcardPolicy: None
{{- end }}
