specVersion: "0.8"
id: training
name: training
annotations:
  - "workflow-type/infrastructure"
version: 0.0.1
start: Training
states:
  - name: Training
    type: inject
    data:
      message: Training...
    end: true
