apiVersion: apps/v1
kind: Deployment
metadata:
  name: move2kube
spec:
  selector:
    matchLabels:
      app: move2kube
  template:
    metadata:
      labels:
        app: move2kube
    spec:
      containers:
        - name: move2kube
          image: quay.io/konveyor/move2kube-ui:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: move2kube-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: move2kube