apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: assessment-with-kn-function
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/assessment-with-kn-function
        env:
        - name: PORT
          value: 8080
