openapi: 3.0.3
info:
  title: Terraform Cloud API
  version: v2
servers:
  - url: https://archivist.terraform.io/v1
security:
  - BearerToken: []
paths:
  /object/{url}:
    post:
      description: Upload URL
      operationId: Upload URL
      parameters:
        - name: url
          in: path
          required: true
          schema: {}
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: object
              format: binary
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/runResponse"
components:
  schemas:
    runResponse:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
