---
  name: Escalation CI pipeline
  
  on:
    workflow_dispatch:
    push:
      paths:
        - escalation-eda/*
    release:
      types: prereleased
  env:
    HELM_REPO_URL: "https://dmartinol.github.io/serverless-workflow-examples"
    ESCALATION_CHART_PATH: "escalation-eda/helm/escalation-eda"
    ESCALATION_SWF_PATH: "escalation-eda/escalation-swf"
    # TODO: one of latest/release
    CHART_REPO: "latest"  
    MVN_OPTS: "-Dmaven.repo.remote=https://repository.jboss.org/nexus/content/groups/public -s escalation-eda/settings.xml"
  jobs:
    build-chart-and-deploy:
      runs-on: ubuntu-latest
      name: Package and deploy a new chart version
      steps:
        - uses: actions/checkout@v3
          with:
            ref: generic-swf

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      
        # - name: Build project with Maven
        #   run: |
        #     mvn ${{ env.MVN_OPTS }} -B package --file escalation-eda/pom.xml -DskipTests

        - name: Set env
          run: |
            echo "ESCALATION_CHART=${{ env.ESCALATION_CHART_PATH }}/Chart.yaml" >> "$GITHUB_ENV"
            echo "ESCALATION_CHART_VERSION=$(mvn ${{ env.MVN_OPTS }} help:evaluate -Dexpression=project.version -q -DforceStdout -f ${{ env.ESCALATION_SWF_PATH }}/pom.xml | sed 's/-SNAPSHOT//g')" >> "$GITHUB_ENV"
            echo "CURRENT_CHART_REPO=charts/${{ env.CHART_REPO }}" >> "$GITHUB_ENV"
            echo "CHART_NAME=$(cat ${{ env.ESCALATION_CHART }} | grep 'name:' | cut -c 7-)" >> "$GITHUB_ENV"
          
        - name: Update chart version
          run: |
            sed -i 's/version: .*/version: ${{ env.ESCALATION_CHART_VERSION }}/g' ${{ env.ESCALATION_CHART }}
            sed -i 's/appVersion: .*/appVersion: ${{ env.ESCALATION_CHART_VERSION }}/g' ${{ env.ESCALATION_CHART }}
  
        # - name: Configure Git
        #   run: |
        #     git config user.name "${{ github.actor }}"
        #     git config user.email "${{ github.actor }}@users.noreply.github.com"
  
        - name: Setup Helm
          uses: azure/setup-helm@v3

        - name: Lint chart
          run: helm lint ${{ env.ESCALATION_CHART_PATH }}
  
        - name: Package chart
          run: helm package ${{ env.ESCALATION_CHART_PATH }}
  
        - name: Push new chart file
          run: |
            git add $ESCALATION_CHART
            if ! git diff-index --quiet HEAD; then
              git commit -m "build: bumped ${{ env.CHART_NAME }} to ${{ env.ESCALATION_CHART_VERSION }} [skip ci]"
              git push
            fi
        # TODO: add tag on release or add released artifact to tag?
        # - name: Push new tag
        #   if: ${{ github.event.inputs.add_tag }}
        #   run: |
        #     git tag "v${{ github.event.inputs.new_semver }}"
        #     git push origin --tags
  
        - name: GH-Pages checkout
          run: |
            git fetch
            git checkout gh_pages
  
        - name: Prepare repository
          run: |
            mkdir -p ${{ env.CURRENT_CHART_REPO }}
            mv *.tgz ${{ env.CURRENT_CHART_REPO }}

        - name: Update repository index
          run: |
            helm repo index --url ${{ env.HELM_REPO_URL }}/${{ env.CURRENT_CHART_REPO }} ${{ env.CURRENT_CHART_REPO }}
  
        - name: Deploy new chart
          run: |
            git add ${{ env.CURRENT_CHART_REPO }}
            git commit -m "chore: deployed chart ${{ env.CHART_NAME }} version ${{ env.ESCALATION_CHART_VERSION }} on repo ${{ env.CURRENT_CHART_REPO }}"
            git push
